### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [FamroFexl/ShulkerLoader#6]
### Describe the Bug

/

### Mod version(s) affected

Latest build

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21

### To Reproduce (If applicable)

Failed to handle packet for /127.0.0.1:51705
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:652) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:401) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.class_1799.method_7985()'
        at net.minecraft.class_1542.unloadShulker(class_1542.java:653) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.handler$zom000$shulkerloader$itemPickupEvent(class_1542.java:611) ~[server-intermediary.jar:?]
        at net.minecraft.class_1542.method_5694(class_1542.java:385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_7341(class_1657.java:654) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:627) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:312) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:588) ~[server-intermediary.jar:?]
        ... 9 more

**Comment by FamroFexl** [comment]
Updated in [v1.0.11](https://github.com/FamroFexl/ShulkerLoader/releases/tag/v1.0.11)

**Comment by venaminecraft** [comment]
Thanks ☺️
